### ISSUE TITLE
Installation of this plugin on Eclipse 03-2019

### ISSUE THREAD

**Issue by ankurjhawar** [trylimits/Eclipse-Postfix-Code-Completion#22]
Hello,
This feature looks very appealing and useful. Thus I tried to install this plugin on Eclipse 03-2019 and it fails. Can you please have a look and assist?
Thanks!

Screenshots for reference:
![image](https://user-images.githubusercontent.com/7464166/56097226-1734df80-5f0f-11e9-9f51-3fed519d81e1.png)

![image](https://user-images.githubusercontent.com/7464166/56097231-27e55580-5f0f-11e9-984d-03fc1924e335.png)

**Comment by trylimits** [comment]
Is there any error message showing up during the installation or does it fail "silently"?

**Comment by ankurjhawar** [comment]
> Is there any error message showing up during the installation or does it fail "silently"?

As per the workspace .log, following is what is there:


!ENTRY org.eclipse.equinox.p2.repository 2 0 2019-04-20 06:45:23.068
!MESSAGE Server returned lastModified <= 0 for https://raw.githubusercontent.com/trylimits/Eclipse-Postfix-Code-Completion/master/org.eclipse.jdt.postfixcompletion.updateSite/target/site/content.jar

!ENTRY org.eclipse.equinox.p2.repository 2 0 2019-04-20 06:46:10.100
!MESSAGE Server returned lastModified <= 0 for https://raw.githubusercontent.com/trylimits/Eclipse-Postfix-Code-Completion/master/org.eclipse.jdt.postfixcompletion.updateSite/target/site/artifacts.jar

!ENTRY org.eclipse.equinox.p2.operations 4 0 2019-04-20 06:48:00.789
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10011 2019-04-20 06:48:00.789
!MESSAGE "JDT Patch to enable Postfix completion in Luna (Required)" is not applicable to the current configuration and will not be installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2019-04-20 06:48:00.805
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10011 2019-04-20 06:48:00.805
!MESSAGE "JDT Patch to enable Postfix completion in Luna (Required)" is not applicable to the current configuration and will not be installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2019-04-20 06:48:00.833
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10011 2019-04-20 06:48:00.833
!MESSAGE "JDT Patch to enable Postfix completion in Luna (Required)" is not applicable to the current configuration and will not be installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2019-04-20 06:48:00.834
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10011 2019-04-20 06:48:00.834
!MESSAGE "JDT Patch to enable Postfix completion in Luna (Required)" is not applicable to the current configuration and will not be installed.

**Comment by thatsIch** [comment]
Works for me

**Comment by thatsIch** [comment]
Sadly this does not work anymore for Eclipse 2020-09 due JDT being incompatible

```
Cannot complete the install because of a conflicting dependency.
        Software being installed: JDT Patch to enable Postfix completion in Luna (Required) 0.0.1.201412091906 (org.eclipse.jdt.postfixcompletion.luna.patch.feature.group 0.0.1.201412091906)
        Software currently installed: Eclipse Java Development Tools 3.18.500.v20200902-1800 (org.eclipse.jdt.feature.group 3.18.500.v20200902-1800)
        Software currently installed: Eclipse Java Web Developer Tools 3.19.0.v202008250115 (org.eclipse.jst.web_ui.feature.feature.group 3.19.0.v202008250115)
        Only one of the following can be installed at once:
                Java Development Tools Core 3.23.0.v20200828-0941 (org.eclipse.jdt.core 3.23.0.v20200828-0941)
                Java Development Tools Core 3.10.0.201412091906 (org.eclipse.jdt.core 3.10.0.201412091906)
        Cannot satisfy dependency:
                From: SSE JSP Source Editor 1.3.0.v202008120247 (org.eclipse.jst.jsp.ui 1.3.0.v202008120247)
                To: osgi.bundle; org.eclipse.jdt.core [3.14.0,4.0.0)
        Cannot satisfy dependency:
                From: Eclipse Java Web Developer Tools 3.19.0.v202008250115 (org.eclipse.jst.web_ui.feature.feature.group 3.19.0.v202008250115)
                To: org.eclipse.equinox.p2.iu; org.eclipse.jst.jsp.ui 0.0.0
        Cannot satisfy dependency:
                From Patch: org.eclipse.jdt.postfixcompletion.luna.patch.feature.group 0.0.1.201412091906 Eclipse Java Development Tools 3.18.500.v20200902-1800 (org.eclipse.jdt.feature.group 3.18.500.v20200902-1800)
                To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.10.0.201412091906,3.10.0.201412091906]
```

I guess you could just redefine the patch requiring a higher version, but not sure how and if it works

**Comment by thatsIch** [comment]
Update: I managed somehow to compile it for Eclipse 2020-09 and the installation works, but the postfix completion does not work anymore. I suspect that a change in the JDT made it incompatible.

https://github.com/commodis/Eclipse-Postfix-Code-Completion

**Comment by thatsIch** [comment]
Apparently Eclipse released an own postfix engine from version 2019-12 onwards

**Comment by trylimits** [comment]
> Apparently Eclipse released an own postfix engine from version 2019-12 onwards

Correct, current Eclipse versions already have _Postfix Completion_ integrated, based on this implementation.
There is actually no need to install this plugin in Eclipse 2020-09.
