### ISSUE TITLE
Provide default templates

### ISSUE THREAD

**Issue by vogella** [trylimits/Eclipse-Postfix-Code-Completion#4]
Hi Nico,

any plans to provide a few default templates with your plug-in? The process of creating them is relatively easy, I documented it today here: http://www.vogella.com/tutorials/EclipseJDTTemplates/article.html

Cheers, Lars

**Comment by trylimits** [comment]
Hi Lars :)

Done. Please see the updated readme ( https://github.com/trylimits/Eclipse-Postfix-Code-Completion/blob/master/README.md ) for a full list of the installed default templates.

Reinstalling from the update site ( https://raw.githubusercontent.com/trylimits/Eclipse-Postfix-Code-Completion/master/org.eclipse.jdt.postfixcompletion.updateSite/target/site/ ) should fix it.

Regards.

**Comment by vogella** [comment]
Looks good, thanks Nico.
