### ISSUE TITLE
Tycho build for your project

### ISSUE THREAD

**Issue by vogella** [trylimits/Eclipse-Postfix-Code-Completion#5]
Could you add a Tycho build for the plug-in / feature? I'm happy to help here, if you are not familiar with Tycho.

**Comment by col-panic** [comment]
Isn't there already? Please check the releng directory!

**Comment by vogella** [comment]
Ah, that confused me. Can you add a pom.xml on the root of the directory pointing to the parent pom.xml? This is typically the setup we use in platform.ui and Maven people expect a pom.xml at the root level of the Git repository

**Comment by col-panic** [comment]
I don't like pom.xml being in the root of the git directory. If I do this, I always have the trouble of managing it within Eclipse as it will not be properly recognized by m2eclipse. If it is part of a regular project, all references (parent etc.) work just fine. 

Try opening the parent pom.xml from a project if its located in root, do you see the same issues, (can not change entries in parent pom, trouble referencinng it ..) or is this a configuration error with me?!

Thanks Lars!

**Comment by vogella** [comment]
Typically the root pom is a reference to your real pom so that both command line users and Eclipse users are happy. 

I send a PR so that you can decide

**Comment by trylimits** [comment]
Added pom.xml in parent directory which points to the pom.xml in the releng project.

**Comment by vogella** [comment]
Thanks, sorry for being slow here and now providing a PR as promissed.

On Tue, Dec 9, 2014 at 7:07 PM, trylimits notifications@github.com wrote:

> Added pom.xml in parent directory which points to the pom.xml in the
> releng project.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trylimits/Eclipse-Postfix-Code-Completion/issues/5#issuecomment-66328353
> .

## 

Geschäftsführer

vogella GmbH

Haindaalwisch 17a, 22395 Hamburg
Amtsgericht Hamburg: HRB 127058
Geschäftsführer: Lars Vogel, Jennifer Nerlich de Vogel
USt-IdNr.: DE284122352
Fax (032) 221739404, Email: lars.vogel@vogella.com, Web:
http://www.vogella.com
